/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apppakage;

import AppPackage.AnimationClass;
import static apppakage.Conect.clear;
import static apppakage.Conect.createTable;
import static apppakage.Conect.insertIntoJw;
import static apppakage.Conect.insertIntoNewWords;
import static apppakage.Conect.insertIntoPrediction;
import static apppakage.Conect.retriveCur;
import static apppakage.Conect.retriveCurjw;
import static apppakage.Conect.retriveNext;
import static apppakage.Conect.retriveNextjw;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.datatransfer.StringSelection;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.border.LineBorder;

/**
 *
 * @author Harshvardhan Patil
 */
public class mainscreen extends javax.swing.JFrame {
    AnimationClass ac=new AnimationClass(); 
    int enable;
    int jpenable;
    Settings s;
    int cw=1;
    int jcw=1;
    int xMouse,yMouse;
    public static String uid;

    /**
     * Creates new form mainscreen
     */
    public mainscreen(String str) throws Exception {
        initComponents();
        uid=str;
        jLabel21.setText("WELCOME "+uid);
        cw=1;
        jcw=1;
        Dimension dim=Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
        animate();
        jTextArea2.setBackground(Color.black);
        jTextArea2.setText("Type status :empty");
        jpenable=1;
        jPanel2.hide();
        s=new Settings();
        SetWallpaper sw=new SetWallpaper();
        sw.setWallpaper();
        if(s.ReadWallpaper().equals("w1"))
        {
            jLabel11.setBorder(new  LineBorder(new Color(51,255,255),1));
        }
        else if(s.ReadWallpaper().equals("w2")){
            jLabel12.setBorder(new  LineBorder(new Color(51,255,255),1));
        }
        Conect c=new Conect(uid);
        createTable();
        jLabel14.hide();
        jLabel15.hide();
        jLabel16.hide();
        jLabel17.hide();
        jLabel18.hide();
        setAllBlankJava();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setOpacity(0.98F);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(">");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255)));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 70, 50, 50));

        jLabel6.setForeground(new java.awt.Color(51, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("X");
        jLabel6.setToolTipText("");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255)));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 20, 30, 30));

        jLabel7.setForeground(new java.awt.Color(51, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("-");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255)));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 20, 30, 30));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 255));
        jLabel3.setText("WORD PREDICTOR");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 590, 60));

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255)));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 410, 6));

        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(51, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 1, true));
        jTextArea1.setCaretColor(new java.awt.Color(51, 255, 255));
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextArea1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextArea1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 470, 610));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 255));
        jLabel5.setText("Start typing....");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jLabel5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel5KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jLabel5KeyTyped(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255)));
        jPanel1.setForeground(new java.awt.Color(51, 255, 255));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 255, 255));
        jLabel8.setText("Developer pannel");

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(210, 210, 210));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255)));
        jScrollPane2.setViewportView(jTextArea2);

        jLabel9.setForeground(new java.awt.Color(51, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ENABLE");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255)));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 137, 380, 620));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255)));
        jPanel2.setOpaque(false);

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 255, 255));
        jLabel10.setText("THEMES");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/theme1.JPG"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/theme2.JPG"))); // NOI18N
        jLabel12.setText("jLabel12");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 140, 380, 610));

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("COPY");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255)));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 140, 30));

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("jLabel14");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255)));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 180, 40));

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("jLabel15");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255)));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 180, 40));

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("jLabel16");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255)));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 180, 40));

        jLabel17.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("jLabel17");
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255)));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 180, 40));

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("jLabel18");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255)));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 180, 40));

        jLabel19.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("ABOUT");
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255)));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 90, 160, 30));

        jLabel21.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 255, 255));
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 20, 220, 30));

        jLabel20.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel20MouseDragged(evt);
            }
        });
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel20MousePressed(evt);
            }
        });
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 60));

        jLabel22.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("CLEAR DATA");
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255)));
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 90, 130, 30));

        jLabel23.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255)));
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 480, 180, 40));

        jLabel24.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255)));
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 535, 180, 40));

        jLabel25.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255)));
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 590, 180, 40));

        jLabel26.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255)));
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 645, 180, 40));

        jLabel27.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255)));
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 700, 180, 40));

        jLabel28.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 255, 255));
        jLabel28.setText("PREDICTED WORDS");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 290, 40));

        jLabel29.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 255, 255));
        jLabel29.setText("PREDICTED JAVA WORDS");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 290, 40));

        jLabel30.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 255, 255));
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 60, 130, 20));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/one.jpg"))); // NOI18N
        jLabel1.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        this.setState(loadAnimation.ICONIFIED);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jTextArea1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyPressed
        jLabel5.setText("Predicting...");
        jTextArea2.setText("Type status : Typing");    // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea1KeyPressed

    private void jTextArea1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyReleased

        jLabel30.setText("");
        
        String str=jTextArea1.getText();
         if(str.isEmpty())
        {
            jLabel5.setText("Start typing...");
            jTextArea2.setText("Type status :empty");

        }
        
        int i,j,k;
        //if space is pressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE)
        {
            setAllBlank();
            setAllBlankJava();
            cw=0;
            jcw=0;
            setDev("Space status:pressed");
            try {
                call1();
            } catch (SQLException ex) {
                Logger.getLogger(mainscreen.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                retriveNext(getCur());
            } catch (SQLException ex) {
                Logger.getLogger(mainscreen.class.getName()).log(Level.SEVERE, null, ex);
            }
            finally{
            try {
                retriveNextjw(getCur());
            } catch (SQLException ex) {
                Logger.getLogger(mainscreen.class.getName()).log(Level.SEVERE, null, ex);
            }
            }

        }
        //space is not pressed
        else{
            setAllBlank();
            setAllBlankJava();
            cw=1;
            jcw=1;
            String cur = null;
            cur=getCur();
            setDev(cur);
            setAllBlank();
            try {
                //String str1[]=retriveCur(cur);
                retriveCur(cur);
            }
            catch (SQLException ex) {
                Logger.getLogger(mainscreen.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("Exception in retriving current");
            }
            finally{
            try {
                setDev("inside mainscreen this is execuited");
                retriveCurjw(cur);
            } catch (SQLException ex) {
                Logger.getLogger(mainscreen.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            
            
            
        }
        

       
    }//GEN-LAST:event_jTextArea1KeyReleased

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5KeyPressed

    private void jLabel5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel5KeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel5KeyTyped

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
            if(enable==0)
        {
            enable=1;
            jLabel9.setText("DISABLE");
            jTextArea2.setForeground(new Color(51,255,255));

        }
        else
        {
            enable=0;
            jLabel9.setText("ENABLE");
            jTextArea2.setForeground(Color.black);
        }    // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
    if(jpenable==1)
    {
        jPanel1.hide();
        jLabel2.setText("<");
        jpenable=0;
        jPanel2.show();
       
    }
    else{
        jPanel2.hide();
        jPanel1.show();
        jLabel2.setText(">");
        jpenable=1;
        
        
            }

    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        ImageIcon i=new ImageIcon(getClass().getResource("/resources/one.jpg"));
        jLabel1.setIcon(i);
        s.WriteWallpaper("w1");
        jLabel11.setBorder(new  LineBorder(new Color(51,255,255),1));
        jLabel12.setBorder(null);
        
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        ImageIcon i=new ImageIcon(getClass().getResource("/resources/two.jpg"));
        jLabel1.setIcon(i);
        s.WriteWallpaper("w2");
        jLabel12.setBorder(new  LineBorder(new Color(51,255,255),1));
        jLabel11.setBorder(null);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        String str=jTextArea1.getText();
        Toolkit.getDefaultToolkit().getSystemClipboard().getContents(null);
        StringSelection stringSelection=new StringSelection(str);
        Toolkit.getDefaultToolkit().getSystemClipboard().setContents(stringSelection, null);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        if(cw==1){
            String sug=jLabel14.getText();
            setTextAreaCur(sug,getCur());
            setDev("current word prediction on");
            afterKeyPressCur();
            
        }
        else{
            String sugn=jLabel14.getText();
            setTextAreaNext(sugn);
            setDev("Next word prediction on");
            afterKeyPressNext();
            
            
        }
        
        
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        if(cw==1){
            String sug=jLabel15.getText();
            setTextAreaCur(sug,getCur());
            setDev("current word prediction on");
            afterKeyPressCur();
            
        }
        else{
            String sugn=jLabel15.getText();
            setTextAreaNext(sugn);
            setDev("Next word prediction on");
            afterKeyPressNext();
            
            
            
        }
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        
        if(cw==1){
            String sug=jLabel16.getText();
            setTextAreaCur(sug,getCur());
            setDev("current word prediction on");
            afterKeyPressCur();
        }
        else{
            String sugn=jLabel16.getText();
            setTextAreaNext(sugn);
            setDev("Next word prediction on");
            afterKeyPressNext();
           
                
            
        }
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        if(cw==1){
            String sug=jLabel17.getText();
            setTextAreaCur(sug,getCur());
            setDev("current word prediction on");
            afterKeyPressCur();
        }
        else{
            String sugn=jLabel17.getText();
            setTextAreaNext(sugn);
            setDev("Next word prediction on");
            afterKeyPressNext();
        }
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        if(cw==1){
            String sug=jLabel18.getText();
            setTextAreaCur(sug,getCur());
            setDev("current word prediction on");
            afterKeyPressCur();
        }
        else{
            String sugn=jLabel18.getText();
            setTextAreaNext(sugn);
            setDev("Next word prediction on");
            afterKeyPressNext();
        }
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        
        About a=new About(this);
        this.hide();
        a.show();
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel20MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_jLabel20MouseDragged

    private void jLabel20MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_jLabel20MousePressed

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        if(jcw==1){
            String sug=jLabel23.getText();
            setTextAreaCur(sug,getCur());
            setDev("current java word prediction on");
            afterKeyPressCur();
            
        }
        else{
            String sugn=jLabel23.getText();
            setTextAreaNext(sugn);
            setDev("Next java word prediction on");
            afterKeyPressNext();
            
            
        }
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here:
        if(jcw==1){
            String sug=jLabel24.getText();
            setTextAreaCur(sug,getCur());
            setDev("current java word prediction on");
            afterKeyPressCur();
            
        }
        else{
            String sugn=jLabel24.getText();
            setTextAreaNext(sugn);
            setDev("Next java word prediction on");
            afterKeyPressNext();
            
            
        }
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        // TODO add your handling code here:
        if(jcw==1){
            String sug=jLabel25.getText();
            setTextAreaCur(sug,getCur());
            setDev("current java word prediction on");
            afterKeyPressCur();
            
        }
        else{
            String sugn=jLabel25.getText();
            setTextAreaNext(sugn);
            setDev("Next java word prediction on");
            afterKeyPressNext();
            
            
        }
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        // TODO add your handling code here:
        if(jcw==1){
            String sug=jLabel26.getText();
            setTextAreaCur(sug,getCur());
            setDev("current java word prediction on");
            afterKeyPressCur();
            
        }
        else{
            String sugn=jLabel26.getText();
            setTextAreaNext(sugn);
            setDev("Next java word prediction on");
            afterKeyPressNext();
            
            
        }
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        // TODO add your handling code here:
        if(jcw==1){
            String sug=jLabel27.getText();
            setTextAreaCur(sug,getCur());
            setDev("current java word prediction on");
            afterKeyPressCur();
            
        }
        else{
            String sugn=jLabel27.getText();
            setTextAreaNext(sugn);
            setDev("Next java word prediction on");
            afterKeyPressNext();
            
            
        }
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        try {
            clear();
            jLabel30.setText("DATA CLEARED");
        } catch (Exception ex) {
            Logger.getLogger(mainscreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel22MouseClicked

    public void animate()
    {
        jLabel3.setLocation(200, 10);
        ac.jLabelXLeft(200,20, 10, 2, jLabel3);
    }
    
    public void call1 () throws SQLException
    {
        //to get current prev and next word
        setDev("Inside call1");
        String str,str2,cw,pw;
        str2=jTextArea2.getText();
        str=jTextArea1.getText();
        jTextArea2.setText(str2+"\nFunction status:into call1");
        StringTokenizer st=new StringTokenizer(str);
        while(st.hasMoreTokens())
        {
           
            str2=str2+"\n"+st.nextToken();
        }
        jTextArea2.setText(str2);
        str2=jTextArea2.getText();
        cw=getCur();
        if(cw=="")
            cw="null";
          setDev("Current wrd:"+cw);
        insertIntoNewWords(cw);
        insertIntoJw(cw);
        //jTextArea2.setText(str2+"\n"+"Current wrd:"+str);
        //str2=jTextArea2.getText();
        pw=getPrev();
        if(pw=="")
            pw="null";
        setDev("Prev wrd:"+pw);
         //jTextArea2.setText(str2+"\n"+"Prev wrd:"+str);
         //setDev("testing");
        insertIntoPrediction(pw,cw);
        
        
        
        
    }
    public String getCur()
    {
        setDev("Inside current");
        String str,str2="",dum;
        str=jTextArea1.getText();
        StringTokenizer st=new StringTokenizer(str);
        while(st.hasMoreTokens())
        {
            
            str2=st.nextToken();
            
            
        }
        if (str2=="")
            return null;
        return str2;
        
    }
    public String getPrev()
    {
        setDev("Inside prev");
        String str,str2="",str3="";
        str=jTextArea1.getText();
        StringTokenizer st=new StringTokenizer(str);
        while(st.hasMoreTokens())
        {
         
            str3=str2;
            str2=st.nextToken();
           
        }
        if (str3=="")
            return null;
        return str3;
        
    }
    public String removeDots(String str)
    {
        String str1;
        str1=str.replaceAll(".", "");
        return str1;
        
    }
    public static void setDev(String str)
    {
        String str1=jTextArea2.getText();
        str1=str1+"\n"+str;
        jTextArea2.setText(str1);
    }
    public void setAllBlank()
    {
        jLabel14.hide();
        jLabel15.hide();
        jLabel16.hide();
        jLabel17.hide();
        jLabel18.hide();
    }
    public void setAllBlankJava()
    {
        jLabel23.hide();
        jLabel24.hide();
        jLabel25.hide();
        jLabel26.hide();
        jLabel27.hide();
    }
    public void setTextAreaCur(String sug,String cur ){
        setDev(sug+"  "+cur);
        String comptext;
        comptext=jTextArea1.getText();
        sug=sug.replaceFirst(cur,"");
        setDev(sug);
        comptext=comptext+sug;
        jTextArea1.setText(comptext);
        
    }
    public void setTextAreaNext(String sug){
        setDev(sug);
        String comptext;
        comptext=jTextArea1.getText();
        comptext=comptext+sug;
        jTextArea1.setText(comptext);
        
        
    }
    public void afterKeyPressCur()
    {
        setAllBlank();
            cw=1;
            String cur = null;
            cur=getCur();
            setDev(cur);
            setAllBlank();
            try {
                //String str1[]=retriveCur(cur);
                 //setAllBlank();
                retriveCur(cur);
            }
            catch (SQLException ex) {
                Logger.getLogger(mainscreen.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("Exception in retriving current");
            }
            
    }
    public void afterKeyPressNext()
    {
        setAllBlank();
        String cur = null;
            cur=getCur();
            setDev(cur);
            setAllBlank();
            try {
                //String str1[]=retriveCur(cur);
                 //setAllBlank();
                retriveCur(cur);
            }
            catch (SQLException ex) {
                Logger.getLogger(mainscreen.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("Exception in retriving current");
            }
    }
            
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    String str;
                    str = uid;
                    new mainscreen(str).setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(mainscreen.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabel14;
    public static javax.swing.JLabel jLabel15;
    public static javax.swing.JLabel jLabel16;
    public static javax.swing.JLabel jLabel17;
    public static javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    public static javax.swing.JLabel jLabel23;
    public static javax.swing.JLabel jLabel24;
    public static javax.swing.JLabel jLabel25;
    public static javax.swing.JLabel jLabel26;
    public static javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    public static javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
